### ISSUE TITLE
método obtemChave().

### ISSUE THREAD

**Issue by almeida-samuel** [kyriosdata/mr#7]
Professor, fui implementar hoje algumas classes é vi que ainda não existe o método obtemChave(), visto, utilizei o método obtemInteiro() visto que é chave é um inteiro.

**Comment by kyriosdata** [comment]
Qual seria a funcionalidade do método obtemChave?

**Comment by almeida-samuel** [comment]
Bem, como foi definido um objeto guarda uma chave(inteiro) de outros objetos que são referenciados por ele, e na última reunião presencial foi mostrado que o método obtemInteiro() poderia ser usado para obter essas chaves, porém, isso poderia causar confusão e foi acordado entre nós a criação de um método obtemChave() que será utilizado especificamente para esse fim.

**Comment by kyriosdata** [comment]
Entendi, já acrescentado.

2015-09-08 14:17 GMT-03:00 Samuel Junio de Almeida <notifications@github.com

> :
> 
> Bem, como foi definido um objeto guarda uma chave(inteiro) de outros
> objetos que são referenciados por ele, e na última reunião presencial foi
> mostrado que o método obtemInteiro() poderia ser usado para obter essas
> chaves, porém, isso poderia causar confusão e foi acordado entre nós a
> criação de um método obtemChave() que será utilizado especificamente para
> esse fim.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kyriosdata/mr/issues/7#issuecomment-138638435.

## 

Atenciosamente,

Fábio Lucena
